// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace MyApp.Data.Models;

public partial class HistoryPrice
{
    public string CurrentPrice { get; set; }

    public string OldPrice { get; set; }

    public DateTime DateChange { get; set; }

    public int idProduct { get; set; }

    public int id { get; set; }

    public int StatusHistory { get; set; }
}