// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;

namespace Project.Models
{
    public partial class ManageProductsContext : DbContext
    {
        public ManageProductsContext()
        {
        }

        public ManageProductsContext(DbContextOptions<ManageProductsContext> options)
            : base(options)
        {
        }

        public virtual DbSet<HistoryPrice> HistoryPrice { get; set; }
        public virtual DbSet<Products> Products { get; set; }

        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.Entity<HistoryPrice>(entity =>
            {
                entity.Property(e => e.Id).HasColumnName("id");

                entity.Property(e => e.CurrentPrice)
                    .IsRequired()
                    .IsUnicode(false);

                entity.Property(e => e.DateChange).HasColumnType("datetime");

                entity.Property(e => e.IdProduct).HasColumnName("idProduct");

                entity.Property(e => e.OldPrice)
                    .IsRequired()
                    .IsUnicode(false);
            });

            modelBuilder.Entity<Products>(entity =>
            {
                entity.Property(e => e.CurrentPrice).IsUnicode(false);

                entity.Property(e => e.DateCreate).HasColumnType("date");

                entity.Property(e => e.ProdType).IsRequired();

                entity.Property(e => e.ProductsName).IsRequired();

                entity.Property(e => e.StatusProduct).HasDefaultValueSql("((1))");
            });

            OnModelCreatingPartial(modelBuilder);
        }

        partial void OnModelCreatingPartial(ModelBuilder modelBuilder);
    }
}