// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace MyApp.Data.Models;

public partial class Products
{
    public int Id { get; set; }
    [Required]
    public string ProductsName { get; set; }
    [Required]
    public string CurrentPrice { get; set; }
    [Required]  
    public string ProdType { get; set; }

    public int StatusProduct { get; set; }

    public DateTime DateCreate { get; set; }
}